#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Run composer inside CLI and pull down
composer_install ()
{

echo "Install drupal with composer..."
	composer global require hirak/prestissimo
	composer create-project drupal-composer/drupal-project:8.x-dev docroot --stability dev --no-interaction

}

# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	copy_settings_file "${PROJECT_ROOT}/.docksal/config/default.settings.local.php" "${SITEDIR_PATH}/settings.local.php"
	# Add local settings snippet to end of settings.php
	cat ${PROJECT_ROOT}/.docksal/config/local-settings-snippet.php >> ${SITEDIR_PATH}/settings.php
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

	# We disable email sending here so site-install does not return an error
	PHP_OPTIONS="-d sendmail_path=`which true`" drush site-install -y --site-name='My Drupal 8 Composer Site'
}

# How log? For eva ava?
time_it_all ()
{
# Project initialization steps
composer_install
fix_permissions
init_settings
site_install
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------
time time_it_all

#-------------------------- END: Execution --------------------------------
